node_js:
- 4
- 5
- 6
language: node_js
sudo: false
script:
- npm run lint
- npm run test-cov
- npm run bench
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
after_success:
  - bash <(curl -s https://codecov.io/bash)
